services:
  unplanned_db:
    image: postgres:15.8
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - unplanned_db:/var/lib/postgresql/data
    networks:
      - unplanned-network
volumes:
  unplanned_db:
networks:
  unplanned-network:
